### ISSUE TITLE
Use Travis secrets only for `master` builds

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#77] opened 2017-09-24 21:56 UTC
Using secrets prevents PRs from forks to complete correctly. Use them only when building `master` (release). Secrets handling is done in `.travis.yml`.

**Comment by jitakirin** [comment] 2017-10-05 06:48
What exactly is the problem here? I forked and created a branch ([here](https://github.com/jitakirin/hexagon/tree/test-travis-secrets)), enabled it in `.travis.yml` (in `branches` config) and it seems to build [OK](https://travis-ci.org/jitakirin/hexagon/builds/283535112).

Yes, it looks like it tries to inject the secrets but just ends up setting gobbledygook but that doesn't seem to affect the build. I'm guessing those variables are only needed for the deploy stage which only executes on master, right?

**Comment by jaguililla** [comment] 2017-10-05 20:34
You went right to the point! The problem only arises in a PR to `master`. But as they will be made only by me (at least in the short term) you can skip this one.

I'll close this task. Thanks for the head up!

**Comment by jaguililla** [comment] 2017-10-05 20:39
Anyway, if you think it is easy and want to solve it. Let me know and I'll reopen it.

**Comment by jitakirin** [comment] 2017-10-07 10:05
Hmm, I'm still not sure what the problem is, I looked at travis logs from previous PRs but can't see any failures. Would you mind if I submitted a PR to master just to see what happens? Not to be merged or anything, I'll close it afterwards, just wanted to see what travis does.

**Comment by jaguililla** [comment] 2017-10-08 21:06
It is OK if you do a PR to `master` just to trigger the error, last time someone created a PR to `master` Travis build didn't start because of security complaints with keys. I cannot find the PR (I relaunched it after and it worked).

**Comment by jitakirin** [comment] 2017-10-11 08:38
So there's one thing I noticed so far, which I'm not sure if it does what you intended.  In `.travis.yml` in `install` phase you have the command `git pull origin master develop`, given that Travis checks out the branch being merged at the very start, this will essentially try to fast-forward it to `develop`.

If you're merging the `develop` branch this is a no-op, but if merging some other branch that was based directly on `master` this would often fail (I imagine, given that `develop` is usually quite a bit ahead) because of conflicts it could result in.

I think Travis will update the checkout to the latest commit of the target branch by default, so a manual pull shouldn't be necessary.  Unless you have a policy that all commits to master should be from `develop` branch, in which case this can detect if a PR wasn't based on that?

**Closed** 2017-10-11 17:28 UTC
Labels: hacktoberfest, help wanted, wontfix
